package com.icq.reborn;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.webkit.*;import android.widget.Toast;import java.io.*;import java.util.*;
public class MainActivity extends Activity{
 WebView w;ValueCallback<Uri[]> fileCb;static final int FILE=43;
 public void onCreate(Bundle b){super.onCreate(b);ask();w=new WebView(this);setContentView(w);WebSettings s=w.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setMediaPlaybackRequiresUserGesture(false);s.setAllowFileAccess(false);s.setAllowContentAccess(true);
  w.setWebViewClient(new WebViewClient(){public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){Uri u=r.getUrl();if("https".equals(u.getScheme())&&"icq.local".equals(u.getHost()))try{return new WebResourceResponse("text/html","UTF-8",getAssets().open("index.html"));}catch(Exception e){}return super.shouldInterceptRequest(v,r);}public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){Uri u=r.getUrl();if("https".equals(u.getScheme())&&"icq.local".equals(u.getHost()))return false;try{startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(Exception e){}return true;}});
  w.setWebChromeClient(new WebChromeClient(){public void onPermissionRequest(PermissionRequest r){runOnUiThread(()->{List<String>a=new ArrayList<>();for(String x:r.getResources()){if(PermissionRequest.RESOURCE_AUDIO_CAPTURE.equals(x)&&ok(Manifest.permission.RECORD_AUDIO))a.add(x);if(PermissionRequest.RESOURCE_VIDEO_CAPTURE.equals(x)&&ok(Manifest.permission.CAMERA))a.add(x);}if(a.isEmpty())r.deny();else r.grant(a.toArray(new String[0]));});}public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> cb,FileChooserParams p){fileCb=cb;try{startActivityForResult(p.createIntent(),FILE);return true;}catch(Exception e){fileCb=null;return false;}}});
  w.addJavascriptInterface(new Bridge(),"NativeBridge");w.loadUrl("https://icq.local/");}
 boolean ok(String p){return Build.VERSION.SDK_INT<23||checkSelfPermission(p)==PackageManager.PERMISSION_GRANTED;}void ask(){if(Build.VERSION.SDK_INT<23)return;ArrayList<String>m=new ArrayList<>();for(String p:new String[]{Manifest.permission.CAMERA,Manifest.permission.RECORD_AUDIO})if(checkSelfPermission(p)!=PackageManager.PERMISSION_GRANTED)m.add(p);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)m.add(Manifest.permission.POST_NOTIFICATIONS);if(!m.isEmpty())requestPermissions(m.toArray(new String[0]),42);}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==FILE&&fileCb!=null){fileCb.onReceiveValue(WebChromeClient.FileChooserParams.parseResult(c,d));fileCb=null;}}
 public class Bridge{@JavascriptInterface public void copy(String t){runOnUiThread(()->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("ICQ Reborn",t));Toast.makeText(MainActivity.this,"Скопировано",Toast.LENGTH_SHORT).show();});}@JavascriptInterface public void share(String t){runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,t);startActivity(Intent.createChooser(i,"Поделиться кодом ICQ Reborn"));});}@JavascriptInterface public void toast(String t){runOnUiThread(()->Toast.makeText(MainActivity.this,t,Toast.LENGTH_SHORT).show());}@JavascriptInterface public void bg(boolean on){runOnUiThread(()->{Intent i=new Intent(MainActivity.this,P2PForegroundService.class);if(on){if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}else stopService(i);});}}
}
